apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: elasticsearch-curator-config
  labels:
    app: elasticsearch-curator
data:
  curator.yml.sample: |-
    client:
      hosts: ['http://{{ELASTIC_URL}}']
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
  curator-actions.yml: |-
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 2 days ^(apm-|filebeat-|metricbeat-).*$
        options:
          disable_action: False
          ignore_empty_list: True
          continue_if_exception: False
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(apm|filebeat|metricbeat)-7.3.0-.*$'
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: hours
          unit_count: 12
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: monitoring
  name: elasticsearch-curator
  labels:
    app: elasticsearch-curator
spec:
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-curator
            image: gjeanmart/docker-elasticsearch-curator
            securityContext:
              runAsUser: 1000
            imagePullPolicy: Always
            command: ["/bin/sh","-c","'/curator/bootup.sh'"]
            volumeMounts:
            - mountPath: /curator/config
              name: elasticsearch-curator-config
            env:
            - name: ELASTIC_URL
              value: "elasticsearch-client.monitoring.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              value:
            - name: ELASTICSEARCH_PASSWORD
              value:
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          volumes:
          - name: elasticsearch-curator-config
            configMap:
              name: elasticsearch-curator-config
