replicaCount: 1

image: ipfs/go-ipfs:v0.4.9

swarm:
  port: 30036
  minConnection: 600
  maxConnection: 900
  gracePeriod: "20s"
  disableBandwidthMetrics: "false"
  disableNatPortMap: "false"
  disableRelay: "false"
  enableAutoNATService: "false"
  enableAutoRelay: "false"
  enableRelayHop: "false"

routing:
  type: dht

service:
  type: NodePort

persistence:
  enabled: true
  ## ipfs data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  size: "8Gi"
  snapshotRules: "P1D P7D P30D"
  accessModes:
    - ReadWriteOnce

ipfscluster:
  enabled: false
  image: ipfs/ipfs-cluster:v0.7.0
  bootstrapperIP:
  secret: 1aebe6d1ff52d96241e00d1abbd1be0743e3ccd0e3f8a05e3c8dd2bbbddb7b93
