apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ethereum.fullname" . }}-geth-config
  labels:
    app: {{ template "ethereum.name" . }}-geth-config
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  networkid: "{{ .Values.geth.genesis.networkId }}"
  genesis.json: |-
    {
        "config": {
            "chainId": {{ .Values.geth.genesis.networkId }},
            "homesteadBlock": 0,
            "eip150Block": 0,
            "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "eip155Block": 0,
            "eip158Block": 0,
            "ByzantiumBlock": 0,
            "ethash": {}
        },
        "difficulty": "0x20000",
        "gasLimit": "0x47e7c5",
        "alloc": {
            {{- range .Values.geth.genesis.accountsToFund }}
            {{ . | quote }}: {
                "balance": "999000000000000000000"
            },
            {{- end }}
            "0x0000000000000000000000000000000000000001": {"balance": "1"}
        }
    }
