kind: Service
apiVersion: v1
metadata:
  name: {{ template "ethereum.fullname" . }}-geth-miner-service
  labels:
    app: {{ template "ethereum.name" . }}-geth-miner-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "ethereum.name" . }}-geth-miner
  type: {{ .Values.geth.miner.service.type }}
  ports:
  - name: rpc
    port: 8545
