apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ipfs.fullname" . }}-ipfs-cluster-secret
  labels:
    app: {{ template "ipfs.name" . }}-ipfs-cluster-secret
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  CLUSTER_SECRET: {{ .Values.ipfscluster.secret | b64enc | quote }}
