apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.data.volumeName }}-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.data.storageClass }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data.volumeSize }}
