---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web3-auth
  labels:
    app: web3-auth
    tier: compute
spec:
  replicas: 2
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web3-auth
        tier: compute
    spec:
      containers:
      - image: kauriorg/web3auth:0.0.24
        command:
          - "java"
          - "-javaagent:/apm-agent.jar"
          - "-Delastic.apm.server_urls=$(ELASTIC_APM_SERVER)"
          - "-Delastic.apm.service_name=web3auth"
          - "-Delastic.apm.service_version=0.0.24"
          - "-Delastic.apm.transaction_sample_rate=0.5"
          - "-Delastic.apm.transaction_max_spans=50"
          - "-Delastic.apm.trace_methods=net.consensys.web3auth.*Controller,net.consensys.web3auth.*Service*"
          - "-Delastic.apm.application_packages=net.consensys.web3auth"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/app.jar"
          - "--spring.config.additional-location=${WEB3AUTH_CONF}"
        imagePullPolicy: Always
        name: web3-auth
        env:
          - name: WEB3AUTH_CONF
            value: /etc/config/web3auth-conf.yml
          - name: KAURI_GATEWAY_URL
            value: monolith.uat:8081
          - name: KAURI_USVC_URL
            value: monolith.uat:8081
          - name: DOMAIN_NAME
            value: ".kauri.io"
          - name: CORS_ORIGIN
            value: "https://kauri.io"
          - name: CORS_HEADERS
            value: "Access-Control-Allow-Headers,Origin,X-Requested-With,Content-Type,Accept,X-Auth-Token,elastic-apm-traceparent"
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://mongo-0.mongo.uat.svc.cluster.local:27017,mongo-1.mongo.uat.svc.cluster.local:27017,mongo-2.mongo.uat.svc.cluster.local:27017/web3auth?replicaSet=rs0
          - name: LOG_LEVEL
            value: TRACE
          - name: KAFKA_ADDRESSES
            value: kafka-uat.uat:9092
          - name: ELASTIC_APM_SERVER
            value: http://apm-server.monitoring.svc.cluster.local:8200
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: web3-auth-config
