---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web3-auth
  labels:
    app: web3-auth
    tier: compute
spec:
  replicas: 2
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web3-auth
        tier: compute
    spec:
      containers:
      - image: kauriorg/web3auth:0.0.17
        command:
          - "java"
          - "-jar"
          - "app.jar"
          - "--spring.config.additional-location=${WEB3AUTH_CONF}"
        imagePullPolicy: Always
        name: web3-auth
        env:
          - name: WEB3AUTH_CONF
            value: /etc/config/web3auth-conf.yml
          - name: KAURI_GATEWAY_URL
            value: monolith.dev2:8081
          - name: KAURI_USVC_URL
            value: monolith.dev2:8081
          - name: DOMAIN_NAME
            value: ".dev2.kauri.io"
          - name: CORS_ORIGIN
            value: "http://localhost:3000,https://dev.kauri.io,https://dev2.kauri.io,https://beta.kauri.io,https://admin.kauri.io"
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://mongo-0.mongo.dev2.svc.cluster.local:27017,mongo-1.mongo.dev2.svc.cluster.local:27017,mongo-2.mongo.dev2.svc.cluster.local:27017/web3auth?replicaSet=rs0
          - name: LOG_LEVEL
            value: TRACE
          - name: KAFKA_ADDRESSES
            value: kafka-dev2.dev2:9092
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: web3-auth-config
