---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web3-auth
  labels:
    app: web3-auth
    tier: compute
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web3-auth
        tier: compute
    spec:
      containers:
      - image: kauriorg/web3auth:0.0.16
        command:
          - "java"
          - "-jar"
          - "app.jar"
          - "--spring.config.additional-location=${WEB3AUTH_CONF}"
        imagePullPolicy: Always
        name: web3-auth
        env:
          - name: WEB3AUTH_CONF
            value: /etc/config/web3auth-conf.yml
          - name: KAURI_GATEWAY_URL
            value: monolith.uat:8081
          - name: KAURI_USVC_URL
            value: monolith.uat:8081
          - name: DOMAIN_NAME
            value: ".kauri.io"
          - name: CORS_ORIGIN
            value: "http://localhost:3000,https://dev.kauri.io,https://dev2.kauri.io,https://kauri.io,https://beta.kauri.io,https://admin.kauri.io"
          - name: SPRING_DATA_MONGODB_HOST
            value: mongo.uat
          - name: SPRING_DATA_MONGODB_DATABASE
            value: test
          - name: LOG_LEVEL
            value: TRACE
          - name: KAFKA_ADDRESSES
            value: kafka-uat.uat:9092
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: web3-auth-config
